name: Auto Push

on:
  push:
    branches:
      - main

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "afsanhq99"
          git config --global user.email "afsan.haque@g.bracu.ac.bd"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Auto-commit changes"
          git push
